### ISSUE TITLE
latest version 0.100.19 not available in conda

### ISSUE THREAD

**Issue by KoichiHashikawa** [conda-forge/r-rgl-feedstock#10]
Hi,
I really appreciate you make rgl available for anaconda.
One of the packages that I like to install depends on rgl 0.100.19 which I had hard time installing to anaconda environment.

Are you working on V0.100.19 available for conda anytime soon?
thanks!

**Comment by dpryan79** [comment]
It'll be available in ~40 minutes.

**Comment by KoichiHashikawa** [comment]
thanks so much @dpryan79 !
